[package]
name = "test_example"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "native"
path = "src/lib.rs"


[dependencies]
realgameengine ={ "path" = "../.." }


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
